RECOGNITION_DATASET=timit
RECOGNITION_PREPROCESS_SOURCE=data/$(RECOGNITION_DATASET)/train
RECOGNITION_PREPROCESS_TARGET=data/recognition/train.pkl
RECOGNITION_TRAIN_MODEL=data/recognition/model.pt

.PHONY: recognition_test recognition_train

$(RECOGNITION_PREPROCESS_TARGET): $(RECOGNITION_PREPROCESS_SOURCE)
	python -m preprocess.preprocess_$(RECOGNITION_DATASET) $(RECOGNITION_PREPROCESS_SOURCE) $(RECOGNITION_PREPROCESS_TARGET)

preprocess_recognition: $(RECOGNITION_PREPROCESS_TARGET)

$(RECOGNITION_TRAIN_MODEL): $(RECOGNITION_PREPROCESS_TARGET)
	python -m train.recognition_$(RECOGNITION_DATASET) $(RECOGNITION_PREPROCESS_TARGET) $(RECOGNITION_TRAIN_MODEL)

train_recognition: $(RECOGNITION_TRAIN_MODEL)
